language: java
install:
  - ant doc
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7
    - os: osx
      env: JAVA_HOME=/usr/libexec/java_home
os:
  - linux
  - osx
