language: java

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ant ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mono; fi

install:
  - ant doc

addons:
  apt:
    packages:
    - mono-xbuild

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
